/**
* City
* Cities
*
* The version of the OpenAPI document: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param title 
 * @param locationType 
 * @param woeid 
 * @param lattLong 
 */
@Serializable
data class City (
    @SerialName(value = "title") val title: kotlin.String? = null,
    @SerialName(value = "location_type") val locationType: kotlin.String? = null,
    @SerialName(value = "woeid") val woeid: kotlin.Int? = null,
    @SerialName(value = "latt_long") val lattLong: kotlin.String? = null
)

