/**
* City
* Cities
*
* The version of the OpenAPI document: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Weather

import com.squareup.moshi.Json
/**
 * 
 * @param consolidatedWeather 
 */

data class WeatherNewsList (
    @Json(name = "consolidated_weather")
    val consolidatedWeather: kotlin.Array<Weather>? = null
)

