/**
* City
* Cities
*
* OpenAPI spec version: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package dev.icerock.moko.network.generated.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param title 
 * @param locationType 
 * @param woeid 
 * @param lattLong 
 */
@Serializable data class City (
    @SerialName("title")
    val title: kotlin.String? = null,
    @SerialName("location_type")
    val locationType: kotlin.String? = null,
    @SerialName("woeid")
    val woeid: kotlin.Int? = null,
    @SerialName("latt_long")
    val lattLong: kotlin.String? = null
) {

}

