/**
* City
* Cities
*
* OpenAPI spec version: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package dev.icerock.moko.network.generated.models

import dev.icerock.moko.network.generated.models.Weather
import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param consolidatedWeather 
 */
@Serializable data class WeatherNewsList (
    @SerialName("consolidated_weather")
    val consolidatedWeather: kotlin.collections.List<Weather>? = null
) {

}

