/**
* City
* Cities
*
* The version of the OpenAPI document: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param title 
 * @param locationType 
 * @param woeid 
 * @param lattLong 
 */

data class City (
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "location_type")
    val locationType: kotlin.String? = null,
    @Json(name = "woeid")
    val woeid: kotlin.Int? = null,
    @Json(name = "latt_long")
    val lattLong: kotlin.String? = null
)

