/**
* City
* Cities
*
* The version of the OpenAPI document: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param weatherStateName 
 * @param applicableDate 
 * @param theTemp 
 * @param windDirectionCompass 
 */

data class Weather (
    @Json(name = "id")
    val id: kotlin.Int? = null,
    @Json(name = "weather_state_name")
    val weatherStateName: kotlin.String? = null,
    @Json(name = "applicable_date")
    val applicableDate: kotlin.String? = null,
    @Json(name = "the_temp")
    val theTemp: java.math.BigDecimal? = null,
    @Json(name = "wind_direction_compass")
    val windDirectionCompass: kotlin.String? = null
)

