/**
* City
* Cities
*
* OpenAPI spec version: 1.0.0
* Contact: lexkraev@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package dev.icerock.moko.network.generated.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param id 
 * @param weatherStateName 
 * @param applicableDate 
 * @param theTemp 
 * @param windDirectionCompass 
 */
@Serializable data class Weather (
    @SerialName("id")
    val id: kotlin.Long? = null,
    @SerialName("weather_state_name")
    val weatherStateName: kotlin.String? = null,
    @SerialName("applicable_date")
    val applicableDate: kotlin.String? = null,
    @SerialName("the_temp")
    val theTemp: kotlin.Double? = null,
    @SerialName("wind_direction_compass")
    val windDirectionCompass: kotlin.String? = null
) {

}

